log_format md_timing '$remote_addr [$time_local] "$request" '
                     'status=$status bytes=$body_bytes_sent '
                     'rt=$request_time urt=$upstream_response_time '
                     'uaddr=$upstream_addr '
                     'ref="$http_referer" ua="$http_user_agent"';

access_log /var/log/nginx/md_timing.log md_timing;